[book]
authors = ["nammon <supamongkon.r@gmail.com>"]
language = "en"
multilingual = false
src = "src"
title = "Learning ZK with NinNin"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
