name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Run after successful completion of Mdbook build workflow
  workflow_run:
    workflows: ["Mdbook build"]
    types:
      - completed

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Disallow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Download the artifact from Mdbook build workflow
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: book
          path: book/

      # Configure Pages
      - name: Setup Pages
        uses: actions/configure-pages@v2

      # Upload artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: book

      # Retrieve and print environment URL for debugging
      - name: Get environment URL
        run: echo "Environment URL: ${{ steps.deployment.outputs.page_url }}"

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
